source "http://rubygems.org"

# web engine
gem "sinatra", "1.3.2"
# service DSL
gem "weasel_diesel"
gem "wd_sinatra"
# gem 'wd_newrelic_rpm', :require => 'newrelic_rpm'

gem 'backports', '2.3.0', :platform => 'ruby_18'
gem 'json', :platform => 'ruby_18'

group :development, :test do
  gem "rack-test", "0.6.1"
  # gem "foreman"
  # gem "puma"
  gem "minitest"
  # gem "guard-puma"
  # gem "guard-minitest"
  gem "rake"
end
